{
 "title": "Auto Scaling",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Derivative kafka consumer lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(deriv(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max[1m]))\r\n"
    }
   ]
  },
  {
   "title": "Backpressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(avg_over_time(flink_taskmanager_job_task_backPressuredTimeMsPerSecond[1m]))"
    }
   ]
  },
  {
   "title": "Consume and produce rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{topic= \"topic\"}[2m]) ",
     "legendFormat": "Produced"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_total[2m]))\n",
     "legendFormat": "Consumed"
    }
   ]
  },
  {
   "title": "Kafka consumer lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(avg_over_time(flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max[1m]))\n",
     "legendFormat": "records"
    }
   ]
  },
  {
   "title": "Task Managers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers"
    }
   ]
  }
 ]
}