# Disable all Prometheus services except "server", since they aren't required
# for the playground.

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

pushgateway:
  enabled: false

server:
  persistentVolume:
    enabled: false
  extraFlags:
#    - web.enable-lifecycle
    ## web.enable-admin-api flag controls access to the administrative HTTP API which includes functionality such as
    ## deleting time series. This is disabled by default.
    - web.enable-admin-api
    ## storage.tsdb.no-lockfile flag controls BD locking
#    - storage.tsdb.no-lockfile
    ## storage.tsdb.wal-compression flag enables compression of the write-ahead log (WAL)
#    - storage.tsdb.wal-compression
  storagePath: "/prometheus/"

# | is required because extraScrapeConfigs is expected to be a string
extraScrapeConfigs: |
  - job_name: 'kubernetes-pods-scrape-every-2s'
    scrape_interval: 5s
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    # Custom
    - source_labels: [__meta_kubernetes_pod_annotation_ververica_com_scrape_every_2s]
      action: keep
      regex: true
    # Boilerplate
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
