apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 8 # here, we configure the scale
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      annotations:
        prometheus.io/port: '9249'
        ververica.com/scrape_every_2s: 'true'
        # prometheus.io/scrape: 'true'
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: 9923/experiments:36
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 500m
            memory: 1000Mi
        securityContext:
          runAsUser: 0
        env:
        args: ["taskmanager"]
        ports:
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query-state
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 60 
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf/
        - name: my-pvc-nfs
          mountPath: /opt/flink/savepoints 
      securityContext:
        fsGroup: 1000
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j-console.properties
            path: log4j-console.properties
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs      

