# Requires: INPUT_RATE_MEAN, INPUT_RATE_MAX_DIVERGENCE
kind: Deployment
apiVersion: apps/v1
metadata:
  name: workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbench
  template:
    metadata:
      labels:
        app: workbench
    spec:
      containers:
      - name: workbench-container
        image: gsiachamis/workbench:3.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 8000m
            memory: 4000Mi
          limits:
            cpu: 8000m
            memory: 4000Mi
        env:
        args: ["mvn", "exec:java", "-Dexec.mainClass=ch.ethz.systems.strymon.ds2.flink.nexmark.sources.BidPersonGeneratorKafka", "-Dexec.args=--generator-parallelism 16 --enable-person-topic true --enable-auction-topic true --load-pattern cosine --use-default-configuration false --cosine-period 60 --max-noise 10000 --input-rate-mean ${INPUT_RATE_MEAN} --input-rate-maximum-divergence ${INPUT_RATE_MAX_DIVERGENCE}"]
