kind: Deployment
apiVersion: apps/v1
metadata:
  name: dhalion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhalion
  template:
    metadata:
      annotations:
        prometheus.io/port: '8000'
        ververica.com/scrape_every_2s: 'true'
      labels:
        app: dhalion
    spec:
      containers:
      - name: python-container
        image: gsiachamis/autoscalers:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        args: ["python", "./", "dhalion"]
        env:
        # Python configurations
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: "UTF-8"

        # Common variables
        - name: USE_FLINK_REACTIVE  # {true, false} - false is default
          value: "false"
        - name: PROMETHEUS_SERVER   # prometheus-server is default
          value: "prometheus-server"
        - name: FLINK_JOBMANAGER_SERVER   # flink-jobmanager-rest:8081 is default
          value: "flink-jobmanager-rest:8081"
        - name: AVAILABLE_TASKMANAGERS # 16 is default
          value: "16"
        - name: OVERPROVISIONING_FACTOR # 1.0 is default
          value: "1.0"
        - name: METRIC_AGGREGATION_PERIOD_SECONDS # 60 is default
          value: "15"
        - name: COOLDOWN_PERIOD_SECONDS # 120 is default
          value: "120"
        - name: ITERATION_PERIOD_SECONDS # 15 is default
          value: "15"
        - name: KUBERNETES_NAMESPACE # default is default
          value: "jkanis-space"

        # Non-reactive functionality
        - name: NONREACTIVE_TIME_AFTER_DELETE_JOB_SECONDS # 4 is default
          value: "4"
        - name: NONREACTIVE_TIME_AFTER_DELETE_POD_SECONDS # 4 is default
          value: "4"
        - name: NONREACTIVE_TIME_AFTER_SAVEPOINT_SECONDS # 4 is default
          value: "4"
        - name: NONREACTIVE_JOB
          value: "ch.ethz.systems.strymon.ds2.flink.nexmark.queries.updated.Query${QUERY}KafkaSource"
        - name: NONREACTIVE_CONTAINER
          value: "gsiachamis/flink-nexmark-queries:1.0"
        - name: NONREACTIVE_SAVEPOINT_TIMEOUT_SECONDS # 60 is default
          value: "60"

        # Dhalion configurations
        - name: DHALION_SCALE_DOWN_FACTOR # 0.8 is default
          value: "0.8"
        - name: DHALION_BUFFER_USAGE_CLOSE_TO_ZERO_THRESHOLD # 0.1 is default
          value: "0.1"
