apiVersion: batch/v1
kind: Job
metadata:
name: flink-jobmanager
spec:
template:
  metadata:
    annotations:
      prometheus.io/port: '9249'
      ververica.com/scrape_every_2s: 'true'
    labels:
      app: flink
      component: jobmanager
  spec:
    restartPolicy: OnFailure
    containers:
      - name: jobmanager
        image: gsiachamis/flink-nexmark-queries:1.0
        imagePullPolicy: Always
        env:
        args: ['standalone-job', '--job-classname', 'ch.ethz.systems.strymon.ds2.flink.nexmark.queries.updated.Query1KafkaSource', '--fromSavepoint', 'test', '--p-sink', 1, '--p-map', 1, '--p-source', 1]
        ports:
          - containerPort: 6123
            name: rpc
          - containerPort: 6124
            name: blob-server
          - containerPort: 8081
            name: webui
        livenessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
          - name: flink-config-volume
            mountPath: /opt/flink/conf
          - name: my-pvc-nfs
            mountPath: /opt/flink/savepoints
        securityContext:
          runAsUser: 0  # refers to user _flink_ from official flink image, change if necessary
    volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
            - key: flink-conf.yaml
              path: flink-conf.yaml
            - key: log4j-console.properties
              path: log4j-console.properties
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs