# Requires:
# EXPERIMENT_DURATION
# WORKLOAD_CONFIGURATION_0: INPUT_RATE_MEAN
# WORKLOAD_CONFIGURATION_1: INPUT_RATE_MAX_DIVERGENCE
# WORKLOAD_CONFIGURATION_2: INPUT_RATE_MAX_NOISE
kind: Deployment
apiVersion: apps/v1
metadata:
  name: workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbench
  template:
    metadata:
      labels:
        app: workbench
    spec:
      containers:
      - name: workbench-container
        image: gsiachamis/workbench:3.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 18000m
            memory: 18000Mi
          limits:
            cpu: 18000m
            memory: 18000Mi
        env:
        args: ["mvn", "exec:java", "-Dexec.mainClass=ch.ethz.systems.strymon.ds2.flink.nexmark.sources.BidPersonGeneratorKafka", "-Dexec.args=--generator-parallelism 36 --enable-person-topic true --enable-auction-topic true --load-pattern cosine  --experiment-length ${EXPERIMENT_DURATION} --use-default-configuration false --cosine-period 60 --input-rate-mean ${WORKLOAD_CONFIGURATION_0} --input-rate-maximum-divergence ${WORKLOAD_CONFIGURATION_1} --max-noise ${WORKLOAD_CONFIGURATION_2}"]
