kind: Deployment
apiVersion: apps/v1
metadata:
  name: workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbench
  template:
    metadata:
      labels:
        app: workbench
    spec:
      containers:
      - name: workbench-container
        image: gsiachamis/workbench:3.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 8000m
            memory: 4000Mi
          limits:
            cpu: 8000m
            memory: 4000Mi
        env:
        args: ["mvn", "exec:java", "-Dexec.mainClass=ch.ethz.systems.strymon.ds2.flink.nexmark.sources.BidPersonGeneratorKafka", "-Dexec.args= --enable-bids-topic true --enable-auction-topic false --enable-person-topic false --load-pattern 'random' --use-default-configuration false --generator-parallelism 16 --epoch-duration-ms 100 --iteration-duration-ms 60000 --initial-input-rate 10000000 --min-divergence 0 --max-divergence 0"]
