# Disable authentication
grafana.ini:
  auth:
    disable_login_form: false
  auth.anonymous:
    enabled: true
    org_role: Editor

# Configure the Prometheus datasource
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      isDefault: true
      url: http://prometheus-server.default.svc

# Configure Grafana to load dashboards from the given directory
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: ''
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

# Don't regenerate admin password on each upgrade
adminPassword: password

# Include a sample Flink dashboard with:
#   --set-file dashboards.default.flink-dashboard.json=grafana-dashboard.json