apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: taskmanager-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flink-taskmanager
  minReplicas: 1
  maxReplicas: 16
  metrics:
  - type: Pods
    pods:
      metric:
        name: utilization
      target:
        type: AverageValue
        averageValue: ${METRIC}
  - type: Pods
    pods:
      metric:
        name: lag_rate
      target:
        type: AverageValue
        averageValue: 1
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 480
   
