kind: Deployment
apiVersion: apps/v1
metadata:
  name: workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbench
  template:
    metadata:
      labels:
        app: workbench
    spec:
      containers:
      - name: workbench-container
        image: gsiachamis/workbench:2.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2000m
            memory: 2000Mi
          limits:
            cpu: 2500m
            memory: 2500Mi
        env:
        # INPUT_RATE_MEAN INPUT_RATE_MAX_DIVERGENCE BIDS_TOPIC_ENABLED PERSON_TOPIC_ENABLED AUCTION_TOPIC_ENABLED
        args: ["mvn", "exec:java", "-Dexec.mainClass=ch.ethz.systems.strymon.ds2.flink.nexmark.sources.BidPersonGeneratorKafka", "-Dexec.args= --load-pattern cosine --use-default-configuration false --cosine-period 60 --max-noise 10000 --input-rate-mean ${INPUT_RATE_MEAN} --input-rate-maximum-divergence ${INPUT_RATE_MAX_DIVERGENCE} --enable-bids-topic ${BIDS_TOPIC_ENABLED} --enable-person-topic ${PERSON_TOPIC_ENABLED} --enable-auction-topic ${AUCTION_TOPIC_ENABLED}"]
