version: '2'
services:

  zookeeper:
  image: wurstmeister/zookeeper
  ports:
  - "2181:2181"

  prometheus:
    image: prom/prometheus:latest
    ports:
    - '9090:9090/tcp'
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
    - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    links:
      - kafka-cluster