global:
  scrape_interval: 15s
  evaluation_interval: 15s

  alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

  scrape_configs: 
  - job_name: 'kafka-cluster'
    scrape_interval: 5s
    static_configs:
    - targets:
        - kafka-cluster:7070
        