# Requires: AVAILABLE_TASKMANAGERS, NAMESPACE
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hpa-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-cpu
  template:
    metadata:
      annotations:
        prometheus.io/port: '8000'
        ververica.com/scrape_every_2s: 'true'
      labels:
        app: hpa-cpu
    spec:
      containers:
      - name: python-container
        image: gsiachamis/autoscalers:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        args: ["python", "./", "hpa-cpu"]
        env:
        # Python configurations
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: "UTF-8"

        # Common variables
        - name: USE_FLINK_REACTIVE  # {true, false} - false is default
          value: "true"
        - name: PROMETHEUS_SERVER   # prometheus-server is default
          value: "prometheus-server"
        - name: FLINK_JOBMANAGER_SERVER   # flink-jobmanager-rest:8081 is default
          value: "flink-jobmanager-rest:8081"
        - name: AVAILABLE_TASKMANAGERS # 16 is default
          value: "${AVAILABLE_TASKMANAGERS}"
        - name: OVERPROVISIONING_FACTOR # 1.0 is default
          value: "1.0"
        - name: METRIC_AGGREGATION_PERIOD_SECONDS # 60 is default
          value: "15"
        - name: COOLDOWN_PERIOD_SECONDS # 120 is default
          value: "120"
        - name: ITERATION_PERIOD_SECONDS # 15 is default
          value: "15"
        - name: KUBERNETES_NAMESPACE # default is default
          value: "${NAMESPACE}"

          # HPA configurations
        - name: HPA_SCALE_DOWN_WINDOW_SECONDS # 300 is default
          value: "300"

          # CPU configurations
        - name: CPU_UTILIZATION_TARGET_VALUE # 0.7 is default
          value: "0.7"