kind: Deployment
apiVersion: apps/v1
metadata:
  name: workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbench
  template:
    metadata:
      labels:
        app: workbench
    spec:
      containers:
      - name: workbench-container
        image: gsiachamis/workbench:2.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2000m
            memory: 2000Mi
          limits:
            cpu: 2500m
            memory: 2500Mi
        env:
        # TODO: Update the execution command with the right args when workbench supports the query.
        args: [ "mvn", "exec:java", "-Dexec.mainClass=ch.ethz.systems.strymon.ds2.flink.nexmark.sources.BidPersonGeneratorKafka", "-Dexec.args= --load-pattern cosine --query 1 --enable-bids-topic true" ]

        #args: ["mvn", "exec:java", "-Dexec.mainClass=ch.ethz.systems.strymon.ds2.flink.nexmark.sources.BidPersonGeneratorKafka", "-Dexec.args=--mode 1 --bids-only 0"]
        #args: ["mvn", "exec:java", "-Dexec.mainClass=ch.ethz.systems.strymon.ds2.flink.nexmark.sources.BidPersonGeneratorKafka", "-Dexec.args=--mode 0 --amplitude 100000 --y-shift 150000 --period 60 --bids-only 0"]
        # args: ["mvn", "exec:java", "-Dexec.mainClass=ch.ethz.systems.strymon.ds2.flink.nexmark.sources.BidSourceFunctionGeneratorKafka", "-Dexec.args=--mode 1 --amplitude 80000 --y-shift 120000 --period 60"]
        # args: ["mvn", "exec:java", "-Dexec.mainClass=ch.ethz.systems.strymon.ds2.flink.nexmark.sources.BidPersonGeneratorKafka", "-Dexec.args=--mode 0 --rate 200000 --bids-only 0"]

      
