kind: Deployment
apiVersion: apps/v1
metadata:
  name: dhalion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhalion
  template:
    metadata:
      annotations:
        prometheus.io/port: '8000'
        ververica.com/scrape_every_2s: 'true'
      labels:
        app: dhalion
    spec:
      containers:
      - name: python-container
        image: jobkanis/dhalion:updated
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        args: ["python", "dhalionOriginalLogic.py"]
        env:
        - name: USE_FLINK_REACTIVE  # {true, false} - false is default
          value: "true"
        - name: PROMETHEUS_SERVER   # prometheus-server is default
          value: "prometheus-server"
        - name: MIN_TASKMANAGERS    # 1 is default
          value: "1"
        - name: MAX_TASKMANAGERS    # 16 is default
          value: "16"
        - name: QUERY  # 1 is default
          value: "3"
        - name: MONITORING_PERIOD_SECONDS # 360 is default
          value: "60"
        - name: METRIC_AGGREGATION_PERIOD_SECONDS # 60 is default
          value: "60"
        - name: BUFFER_USAGE_CLOSE_TO_ZERO_THRESHOLD # 0.1 is default
          value: "0.1"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: "UTF-8" 
  
